Vendor,Layer #,Layer Name,Layer Alias,Target Size,Cost Profile,Deployment Friction,Maturity Phase,Category,Core Differentiator,Identity Score,Data Score,Runtime Score,Governance Score,Conf: Size,Conf: Cost,Conf: Friction,Conf: Differentiator,Conf: Scores,Integrates With,Competitive Overlaps,Founded,Funding,HQ,Last Verified,Verified By,Notes
Okta,1,AI identity & machine access,The front door,Enterprise,$$$,Medium,Walk,Platform IAM,Dominant IAM. Pre-built AI/ML service integrations and adaptive MFA — the default enterprise identity backbone.,95,20,10,30,5,4,4,5,3,"Aembit, CrowdStrike, Credo AI, Microsoft Entra ID",Microsoft Entra ID (direct competitor for Azure shops); Astrix Security (NHI overlap),2009,Public (OKTA),"San Francisco, CA",2025-Q2,,
Aembit,1,AI identity & machine access,The front door,"Mid-Market, Enterprise",$$,Low,Crawl,AI-Native Startup,Workload-to-workload identity without secrets. Purpose-built for M2M access — the gap Okta doesn't close.,85,15,10,15,4,3,4,5,3,"Okta, CrowdStrike, Protect AI, HashiCorp Vault",Astrix Security (NHI discovery overlap); Token Security (machine credential overlap),2021,Series A ($16.6M),"Silver Spring, MD",2025-Q2,,
KeyCard,1,AI identity & machine access,The front door,"SMB, Mid-Market",$,Low,Crawl,AI-Native Startup,"Lightweight API key governance. Hardcoded secrets to managed credentials in days, not quarters.",70,10,5,10,3,2,3,4,2,"Prompt Security, Harmonic Security",Aembit (API key management overlap at mid-market),2023,Seed (est.),Unknown,2025-Q2,,"LOW CONFIDENCE — verify funding, pricing, HQ"
Microsoft Entra ID,1,AI identity & machine access,The front door,"Mid-Market, Enterprise",$$,Medium,Walk,Big Platform,Native Azure/Copilot identity layer. Conditional access policies for AI workloads. Free for M365 E5 customers.,90,25,15,35,5,5,4,5,4,"Okta, CrowdStrike, Microsoft Purview, Microsoft Defender",Okta (direct IAM competitor); Astrix Security (NHI features overlap),2014,Public (MSFT),"Redmond, WA",2025-Q2,,
Astrix Security,1,AI identity & machine access,The front door,"Mid-Market, Enterprise",$$,Low,Crawl,AI-Native Startup,"Non-human identity lifecycle management. Discovers every API key, OAuth token, and service account connected to your AI stack.",82,30,10,25,4,3,3,4,3,"Okta, Aembit, CrowdStrike",Aembit (NHI focus overlap); Token Security (credential discovery overlap); Okta (NHI features emerging),2021,Series B ($45M),"Tel Aviv, Israel",2025-Q2,,
Harmonic Security,2,Prompt guardrails & data security,The brain,"Mid-Market, Enterprise",$$,Low,Crawl,AI-Native Startup,"""Coach, don't block"" — sub-500ms inline guidance nudges users from data leakage. Behavioral DLP for AI.",15,92,10,40,4,3,4,5,3,"Okta, Lasso Security, Credo AI, KeyCard, Microsoft Purview",Nightfall AI (DLP overlap for GenAI); Lakera (prompt-level overlap); Microsoft Purview (enterprise DLP overlap),2023,Series A ($17.5M),"San Francisco, CA",2025-Q2,,
Token Security,2,Prompt guardrails & data security,The brain,Mid-Market,$$,Medium,Walk,AI-Native Startup,Discovers and vaults every non-human identity token. Eliminates the #1 AI attack vector: orphaned service credentials.,60,80,20,25,3,3,3,4,3,"Okta, Aembit, CrowdStrike",Astrix Security (NHI discovery overlap); Aembit (machine credential overlap),2022,Series A (est.),"Tel Aviv, Israel",2025-Q2,,Verify funding round details
Prompt Security,2,Prompt guardrails & data security,The brain,"SMB, Mid-Market, Enterprise",$$,Low,Crawl,AI-Native Startup,"Full-spectrum prompt injection defense across all LLM providers. Real-time I/O filtering, 1-line SDK.",10,88,30,20,4,3,4,5,3,"Harmonic Security, KeyCard, Lasso Security, CrowdStrike",Lakera (direct competitor — prompt injection); AWS Bedrock Guardrails (native prompt filtering overlap),2023,Series A ($18M),"Tel Aviv, Israel",2025-Q2,,
Lasso Security,2,Prompt guardrails & data security,The brain,"Mid-Market, Enterprise",$$,Medium,Walk,AI-Native Startup,LLM interaction monitoring with full conversation audit trails. Maps shadow AI usage and enforces data boundaries.,20,75,15,55,3,2,3,4,2,"Harmonic Security, Prompt Security, Credo AI",Harmonic Security (shadow AI detection overlap); Microsoft Purview (audit trail overlap),2023,Seed ($6M),"Tel Aviv, Israel",2025-Q2,,LOW CONFIDENCE — verify pricing model
Lakera,2,Prompt guardrails & data security,The brain,"Mid-Market, Enterprise",$$,Low,Crawl,AI-Native Startup,Lakera Guard — real-time prompt injection and data exfil defense. Gandalf challenge proved the tech publicly.,10,86,25,15,4,3,4,5,3,"Prompt Security, Harmonic Security, Microsoft Defender",Prompt Security (direct competitor — prompt injection); AWS Bedrock Guardrails (native overlap),2021,Series A ($20M),"Zurich, Switzerland",2025-Q2,,
Microsoft Purview,2,Prompt guardrails & data security,The brain,Enterprise,$$,Medium,Walk,Big Platform,"AI-aware DLP extending to Copilot, ChatGPT Enterprise, and custom LLM apps. Sensitivity labels propagate into AI context.",15,82,10,60,5,4,4,4,4,"Microsoft Entra ID, Microsoft Defender, Harmonic Security, Credo AI",Harmonic Security (DLP overlap); Nightfall AI (DLP overlap); Lasso Security (audit overlap),2022,Public (MSFT),"Redmond, WA",2025-Q2,,
Nightfall AI,2,Prompt guardrails & data security,The brain,"SMB, Mid-Market",$,Low,Crawl,AI-Native Startup,AI-native DLP for SaaS and GenAI apps. Detects PII/PHI/secrets in LLM interactions with pre-trained ML classifiers.,10,78,10,30,4,4,4,5,3,"Slack, GitHub, ChatGPT, Salesforce",Harmonic Security (GenAI DLP overlap); Microsoft Purview (enterprise DLP overlap),2019,Series B ($46M),"San Francisco, CA",2025-Q2,,
CrowdStrike,3,AI workload & runtime protection,The body,Enterprise,$$$,High,Run,Platform Security,Charlotte AI threat hunting + Falcon runtime sensors. Real-time model inference monitoring at kernel level.,25,20,95,35,5,5,4,5,4,"Okta, Aembit, Token Security, HiddenLayer, Protect AI, Microsoft Entra ID",Wiz (CSPM/AI-SPM overlap); Microsoft Defender for AI (Azure runtime overlap); HiddenLayer (adversarial detection overlap),2011,Public (CRWD),"Austin, TX",2025-Q2,,
Protect AI,3,AI workload & runtime protection,The body,"Mid-Market, Enterprise",$$,Medium,Walk,AI-Native Startup,ML supply chain security — ModelScan scans model files and pipelines for vulnerabilities before production.,10,25,82,40,4,3,3,5,3,"CrowdStrike, Aembit, Credo AI, HiddenLayer",HiddenLayer (model security overlap); Wiz (AI pipeline discovery overlap),2022,Series B ($60M),"Seattle, WA",2025-Q2,,
HiddenLayer,3,AI workload & runtime protection,The body,Enterprise,$$$,High,Run,AI-Native Startup,"AIDR — real-time adversarial ML detection for model manipulation, evasion, and extraction attacks in production.",10,15,88,30,4,3,3,5,3,"CrowdStrike, Robust Intelligence (Cisco), Protect AI",Protect AI (model security overlap); CrowdStrike (runtime detection overlap at AI layer),2022,Series A ($50M),"Austin, TX",2025-Q2,,
Wiz,3,AI workload & runtime protection,The body,"Mid-Market, Enterprise",$$$,Medium,Walk,Platform Security,"AI-SPM. Discovers every AI pipeline, model, and dataset across cloud environments. Auto-maps AI bill of materials.",20,35,80,50,5,4,4,5,4,"CrowdStrike, Okta, Microsoft Defender, AWS Security Hub",CrowdStrike (CSPM overlap); Microsoft Defender for AI (Azure AI posture overlap),2020,Acquired by Google ($32B),"New York, NY",2025-Q2,,
Microsoft Defender for AI,3,AI workload & runtime protection,The body,Enterprise,$$,Medium,Walk,Big Platform,"Threat protection for Azure AI services. Detects jailbreaks, prompt injections, and credential theft in Azure OpenAI.",20,30,75,40,5,4,4,4,3,"Microsoft Entra ID, Microsoft Purview, CrowdStrike, Wiz",CrowdStrike (runtime overlap for Azure); Wiz (AI posture overlap); Prompt Security (prompt injection overlap),2024,Public (MSFT),"Redmond, WA",2025-Q2,,
AWS Bedrock Guardrails,3,AI workload & runtime protection,The body,"Mid-Market, Enterprise",$,Low,Crawl,Big Platform,"Native guardrails for Amazon Bedrock. Content filtering, PII redaction, topic blocking — free tier for Bedrock users.",10,40,65,25,5,5,5,5,4,"AWS Security Hub, CrowdStrike",Prompt Security (prompt filtering overlap); Lakera (guardrails overlap for AWS users),2023,Public (AMZN),"Seattle, WA",2025-Q2,,
Credo AI,4,"AI governance, risk & compliance",The rulebook,"Mid-Market, Enterprise",$$,Medium,Walk,AI-Native Startup,"Automated AI risk assessments mapped to EU AI Act, NIST AI RMF, and ISO 42001. Compliance as a CI/CD gate.",15,30,15,92,4,3,3,5,3,"Harmonic Security, Lasso Security, Protect AI, Okta, Microsoft Purview",Holistic AI (AI audit overlap); Robust Intelligence (governance overlap); IBM watsonx.governance (enterprise GRC overlap),2020,Series B ($46M),"Palo Alto, CA",2025-Q2,,
Robust Intelligence (Cisco),4,"AI governance, risk & compliance",The rulebook,Enterprise,$$$,High,Run,Platform Security,"Continuous AI red-teaming and validation. Post-Cisco acquisition, bundled with enterprise networking for AI firewall.",20,25,40,88,5,4,4,4,3,"CrowdStrike, HiddenLayer, CalypsoAI",Credo AI (governance overlap); CalypsoAI (policy gateway overlap); HiddenLayer (validation overlap),2019,Acquired by Cisco,"San Francisco, CA",2025-Q2,,
CalypsoAI,4,"AI governance, risk & compliance",The rulebook,Enterprise,$$$,Medium,Run,AI-Native Startup,"LLM gateway with per-user, per-model policy enforcement. Strong in regulated verticals — finserv and defense.",30,45,25,85,3,3,3,4,3,"Robust Intelligence (Cisco), Credo AI, Okta",Robust Intelligence (policy/gateway overlap); Credo AI (governance overlap); Microsoft Purview (DLP gateway overlap),2018,Series A ($23M),"San Diego, CA",2025-Q2,,Verify current customer count
Holistic AI,4,"AI governance, risk & compliance",The rulebook,"Mid-Market, Enterprise",$$,Low,Walk,AI-Native Startup,AI audit and risk management platform. NYC Local Law 144 compliance pioneer. Strong bias/fairness auditing.,10,20,10,80,4,3,3,4,3,"Credo AI, Microsoft Purview",Credo AI (direct competitor — AI governance); IBM watsonx.governance (audit overlap),2018,Series A ($10M),"London, UK",2025-Q2,,
IBM watsonx.governance,4,"AI governance, risk & compliance",The rulebook,Enterprise,$$$,High,Run,Big Platform,"Enterprise AI lifecycle governance — model factsheets, drift detection, bias monitoring. Deep hybrid cloud integration.",15,25,30,82,5,4,4,4,4,"IBM Cloud Pak, CrowdStrike, Okta",Credo AI (governance overlap); Holistic AI (audit overlap); Robust Intelligence (enterprise GRC overlap),2023,Public (IBM),"Armonk, NY",2025-Q2,,
Arize AI,5,AI observability & monitoring,The nervous system,"Mid-Market, Enterprise",$$,Low,Walk,AI-Native Startup,"ML observability — LLM tracing, evaluation, prompt debugging. Open-source Phoenix library is the community anchor.",5,30,60,45,4,3,4,5,3,"Protect AI, Credo AI, Wiz, Datadog LLM Observability",Galileo AI (direct competitor — LLM eval); WhyLabs (observability overlap); Datadog (APM-native overlap),2020,Series B ($38M),"Berkeley, CA",2025-Q2,,
Galileo AI,5,AI observability & monitoring,The nervous system,"Mid-Market, Enterprise",$$,Low,Walk,AI-Native Startup,"GenAI evaluation and monitoring — hallucination detection, RAG quality scoring, prompt optimization.",5,35,55,50,3,2,3,4,2,"Arize AI, Credo AI, Protect AI",Arize AI (direct competitor); WhyLabs (LLM monitoring overlap); Datadog (observability overlap),2021,Series A ($18M),"San Francisco, CA",2025-Q2,,LOW CONFIDENCE — verify pricing and customer count
WhyLabs,5,AI observability & monitoring,The nervous system,"Mid-Market, Enterprise",$$,Low,Crawl,AI-Native Startup,"AI observability with LangKit for LLM monitoring. Detects data drift, toxicity, PII leakage, jailbreaks in real-time.",5,50,60,35,4,3,4,5,3,"Arize AI, Protect AI, AWS Bedrock Guardrails",Arize AI (observability overlap); Datadog (monitoring overlap); Nightfall AI (PII detection overlap),2019,Series B ($30M),"Seattle, WA",2025-Q2,,
Datadog LLM Observability,5,AI observability & monitoring,The nervous system,"Mid-Market, Enterprise",$$,Low,Walk,Platform Security,"LLM monitoring native to Datadog APM. Traces prompts, latency, token cost, error rates. Zero new vendor for DD customers.",5,25,70,30,5,5,5,5,4,"CrowdStrike, Wiz, Arize AI, AWS Bedrock Guardrails",Arize AI (direct competitor for non-DD shops); WhyLabs (monitoring overlap); Galileo AI (eval overlap),2023,Public (DDOG),"New York, NY",2025-Q2,,